# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000

runner: "episode_uesm"
run: "run_uesm"

rwd_int_lambda: 1
rwd_int_lambda_epi: 0.0000005
rwd_counter_lambda: 0.001
rwd_mask_lambda: 1
rwd_ext_lambda: 1

ball_counter: False


per_ext_lambda: 20
per_int_lambda: 1


agent: "nn"

buffer_name: "episode_buffer_per"
buffer_epsilon: 0.001
buffer_alpha: 1
buffer_alpha_epi: 0.0002
buffer_beta: 0.4
buffer_beta_increment_per_sampling: 0.0001
buffer_abs_err_upper: 500
buffer_size: 5000  # 5000
# update the target network every {} episodes
# debug
target_update_interval: 400 # 200

mask_batch: 128 #128
mask_update_interval: 200  # 200
episode_before_sample: 32 # 32
batch_size: 32
test_nepisode: 32

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_lambda_learner" # usm
td_lambda: True
lambdaa: 0.9
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
counter_limit: 30

name: "qmix_uesm"
