env: hh_island

env_args:
  reward_scale: 1.0
  n_action: 6
  n_agent: 2
  episode_length: 300
  map_name: "hh_island"
  size: 10
  grid_size: 11
  s_data_path: "./results/hh/"
  s_try_num: 0
  num_env: 1
  seed: null
  island_partial_obs: False
  island_agent_max_power: 11
  island_wolf_max_power: 9
  island_wolf_recover_time: 5
  i_num_landmark: 9
  alg_name: "qmix"

test_greedy: True
test_nepisode: 2
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 6150000
batch_size: 2
seed: null